<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite errors="0" failures="1" hostname="LENOVO" name="pytest" skipped="0" tests="1" time="0.055" timestamp="2020-04-26T12:39:41.310481"><testcase classname="test_1" file="test_1.py" line="2" name="test_login" time="0.001"><failure message="NameError: name &apos;user_id&apos; is not defined">def test_login():
&gt;       assert user_id == &apos;greggwilliams58@gmail.com&apos;
E       NameError: name &apos;user_id&apos; is not defined

test_1.py:4: NameError</failure></testcase></testsuite></testsuites>